// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjqnebeogdameimhzmet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcW5lYmVvZ2RhbWVpbWh6bWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTAxMzUsImV4cCI6MjA3MDgyNjEzNX0.7KCMySPprdv6bdzGYQlFdqSIqyFNF3KQOV25mdqIFu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});